name: Content Request
description: Suggest new guides, tutorials, or major improvements to the documentation
labels: [documentation, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea to improve our documentation!
  - type: textarea
    attributes:
      label: Is your request related to a problem?
      description: |
        A clear and concise description of what the problem is or what information is missing.
      placeholder: |
        I'm always frustrated when I can't find information about [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the content you'd like
      description: |
        A clear and concise description of the documentation, guide, or tutorial you want added.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or references about the content request.
