name: Issue Translator
on:
  issue_comment: { types: [created] }
  issues: { types: [opened] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: usthe/issues-translate-action@b41f55ddc81d7d54bd542a4f289fe28ec081898e
        with:
          # Decide whether to modify the issue title
          # The robot account @Issues-translate-bot must have modification permissions.
          # Invite @Issues-translate-bot to your project or use your custom bot.
          IS_MODIFY_TITLE: false
          CUSTOM_BOT_NOTE: The issue is not in English. It has been translated automatically.
